export const data = {
  heading: "Post-Graduate Courses Offered",
  colHeading: ["Courses", "Duration"],
  data: [
    ["MBA", "2years"],
    ["PGD in Hotel Management", "1 year"],
    ["M.Sc in Data Science", "2 years"],
    ["Masters of Business Analytics", "3 years"],
    ["MTech", "2 years"],
    ["MCom", "2 years"],
    ["PGDM", "2 years"],
    ["LLB(Hons)", "3 years"],
    ["MCA", "2 years"],
    ["PGP-BAT", "1 year"],
  ],
};

export const pg = [
  "MBA",
  "PGD in Hotel Management",
  "M.Sc in Data Science",
  "Masters of Business Analytics",
  "MTech",
  "MCom",
  "PGDM",
  "LLB(Hons)",
  "MCA",
  "PGP-BAT",
];

export const degrees = [
  "Science",
  "Commerce",
  "Arts",
  "Diploma",
  "Bachelor of Mass Media (BMM)",
  "Bachelor of Arts (B.A)",
  "Bachelor of Engineering (B.E.)",
  "Bachelor of Technology (B.Tech.)",
  "Bachelor of Pharmacy (B.Pharm.)",
  "Bachelor of Architecture (B.Arch.)",
  "Bachelor of Science (B.Sc.)",
  "Bachelor of Commerce (B.Com.)",
  "Bachelor of Management Studies (B.M.S.)",
  "Bachelor of Education (B.Ed.)",
  "Bachelor of Fine Art (B.F.A.)",
  "Bachelor of Performing Art (B.P.A.)",
  "Bachelor’s Degree in Library & Information Science (B.L.I.Sc.)",
  "Bachelor Of Vocational Program (B. Voc)",
  "Bachelor of Law (LL.B.)",
  "Bachelor in Paint Technology",
  "Bachelor in Interior Design",
  "Bachelor in Animation",
  "Bachelor in Visual Effects",
  "Bachelor in Film Art",
  "Bachelor in Screen Writing",
  "Bachelor in Film Production & Management",
  "Bachelor in Psychological Health & Behavioral Science",
  "Bachelor in Biomedical Instrumentation Science",
  "Bachelor in Capital Market",
  "Bachelor Of Dental Surgery (BDS)",
  "MBBS",
  "Bachelor Of Design (B. Des)",
  "Bachelor of Hospital Management (BHM)",
  "Bachelor of Hotel Management (BHM)",
  "Bachelor of Business Administration (BBA)",
  "Bachelor of Financial Markets (BFM)",
  "Bachelor of Social Work (BSW)",
  "Bachelor of Business Management (BBM)",
  "Others",
];

export const fields = [
  "Others",
  "Interior Design",
  "Jewellery Design",
  "Fashion Communication",
  "Fashion Business Management",
  "Photography",
  "Hair and Make-up Artistry",
  "Maritime Studies",
  "Nautical Science",
  "Logistics",
  "Marine Engineering",
  "Performing Arts",
  "Fashion Design",
  "Communication Design",
  "Engineering",
  "Management",
  "Arts, Sciences",
  "Pharmacy",
  "Law",
  "Film Making",
  "Journalism",
  "Biotechnology",
  "Dentistry",
  "Social Sciences",
  "Study Abroad",
  "Global Education",
  "Study Abroad Prep",
  "Luxury Management",
  "Product Design",
  "Visual Arts",
  "Sports Management",
  "Artificial Intelligence",
  "Design Thinking & Innovation",
  "Animation",
  "VFX",
  "Film Making",
  "Acting",
];
